// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using System.Collections.ObjectModel;
using UnityEngine;


public partial class PlayerShipClassNode : System.ComponentModel.INotifyPropertyChanged {
    
    private String _NewClassProperty;
    
    private List<String> _NewClassCollection;
    
    public event PropertyChangedEventHandler PropertyChanged;
    protected virtual void OnPropertyChanged(string propertyName){ PropertyChangedEventHandler handler = PropertyChanged; if (handler != null) handler(this, new PropertyChangedEventArgs(propertyName)); }
    public virtual String NewClassProperty {
        get {
            return this._NewClassProperty;
        }
        set {
            _NewClassProperty = value;
            OnPropertyChanged("NewClassProperty");
        }
    }
    
    public virtual List<String> NewClassCollection {
        get {
            return this._NewClassCollection;
        }
        set {
            _NewClassCollection = value;
        }
    }
}
